//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YuGiOh01
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carta
    {
        public int IdCarta { get; set; }
        public string Nome { get; set; }
        public Nullable<int> Nivel { get; set; }
        public int NumeroCard { get; set; }
        public Nullable<int> PontosAtaque { get; set; }
        public Nullable<int> PontosDefesa { get; set; }
        public string Descricao { get; set; }
        public int IdTipoCarta { get; set; }
        public Nullable<int> IdAtributo { get; set; }
        public Nullable<int> IdIcone { get; set; }
    
        public virtual Atributo Atributo { get; set; }
        public virtual Icone Icone { get; set; }
        public virtual TipoCarta TipoCarta { get; set; }
    }
}
