//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YuGiOh01
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonstroPendulo
    {
        public int IdMonstroPendulo { get; set; }
        public string Descricao { get; set; }
        public int IdMonstroEfeito { get; set; }
    
        public virtual TipoMonstroEfeito TipoMonstroEfeito { get; set; }
    }
}
