//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YuGiOh01
{
    using System;
    using System.Collections.Generic;
    
    public partial class Monstro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Monstro()
        {
            this.TipoMonstroEfeitoes = new HashSet<TipoMonstroEfeito>();
        }
    
        public int IdMonstro { get; set; }
        public string Descricao { get; set; }
        public int IdTipoCarta { get; set; }
    
        public virtual TipoCarta TipoCarta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TipoMonstroEfeito> TipoMonstroEfeitoes { get; set; }
    }
}
